# Zebra Mussels
#### *Dreissena polymorpha*
---

In [30]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [31]:
import sys

import numpy as np
import pandas as pd

import flbs_ais.nas as nas

#### Database Species Search Results

In [32]:
search_result = nas.species_search('Dreissena', 'polymorpha')
search_string = nas.species_string(search_result)
print(search_string)

speciesID: 5
itis_tsn: 81339
group: Mollusks-Bivalves
family: Dreissenidae
genus: Dreissena
species: polymorpha
subspecies:
variety:
authority: (Pallas, 1771)
common_name: zebra mussel
native_exotic: Exotic
Fresh/Marine/Brackish: Freshwater

---
## Dataframe for zebra mussels

In [33]:
api_key = ""
with open("../tmp/api_key.txt", 'r') as file:
    api_key = file.readline()
api_df = nas.getdf(5, keep_columns=None, limit=-1, api_key=api_key)
print(f"Results: {len(api_df)}")
api_df.head()

Results: 7783

,specimennumber,speciesid,group,family,genus,species,scientificname,commonname,country,state,...,year,month,day,status,comments,recordtype,disposal,museumcatnumber,freshmarineintro,references
0,116074,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,Ohio,...,1990,3,NaN,established,Observed in and around the 61 cm and 76 cm int...,Personal communication,,,Freshwater,[]
1,116075,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,ONT,...,1990,4,NaN,established,Data from various monitoring programs.,Literature,,,Freshwater,"[{'key': 13755, 'refType': 'Other', 'year': 19..."
2,116076,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,New York,...,1990,4,NaN,established,Data from sampling plates and field observations.,Personal communication,,,Freshwater,[]
3,116077,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,New York,...,1990,9,17.0,established,Data from sampling plates and field observatio...,Personal communication,,,Freshwater,[]
4,116078,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,New York,...,1990,9,17.0,established,Data from sampling plates and buoy inspections.,Personal communication,,,Freshwater,[]

---
## List most common references

In [34]:
api_ref_count = nas.ref_counts(api_df)
print(nas.ref_string(api_ref_count, limit=5))

--------
Most common reference 1

Total Occurrences:  2945
--------

--------
Most common reference 2

Source number:      1
Title:              Invader invaded: population dynamics of zebra mussels&nbsp;(<em>Dreissena polymorpha</em>) and quagga mussels (<em>Dreissena&nbsp;rostriformis bugensis</em>) in polymictic Oneida Lake, NY, USA&nbsp;(1992&ndash;2013)
Author:             Hetherington, A.L., L.G. Rudstam, R.L. Schneider, K.T. Holeck, C.W. Hotaling, J.E. Cooper, and J.R. Jackson
Publisher:
Publisher Location:
Year:               2019
Reference Type:     Journal Article

Source number:      2
Title:              Lakewide zebra and quagga mussel summary, Oneida Lake, New York, 1992 to present
Author:             Rudstam, L.G.
Publisher:          Knowledge Network for Biocomplexity
Publisher Location:
Year:               2019
Reference Type:     Database

Total Occurrences:  681
--------

--------
Most common reference 3

Source number:      1
Title:              Zebra mussel sightings (unpublished data).
Author:             Ontario Federation of Anglers and Hunters.
Publisher:
Publisher Location:
Year:               2006
Reference Type:     Database

Total Occurrences:  668
--------

--------
Most common reference 4

Source number:      1
Title:              Exotic aquatic mollusk collections in the Illinois Natural History Survey.
Author:             Vinsel, R., and J. Tiemann
Publisher:          Illinois Natural History Survey
Publisher Location: Champaign, IL
Year:               2016
Reference Type:     Database

Total Occurrences:  435
--------

--------
Most common reference 5

Source number:      1
Title:              Lakes and rivers with invasives species
Author:             Wisconsin Department of Natural Resources (WI DNR).
Publisher:          Wisconsin Department of Natural Resources
Publisher Location: Madison, WI
Year:               2017
Reference Type:     Database

Total Occurrences:  301
--------

---
## CSV Information

In [35]:
csv_df = nas.process_csv_df("../tmp/NAS-Data-ZebraMussel.csv")
print(f"Results: {len(csv_df)}")
csv_df.head()

Results: 7785

,specimennumber,speciesid,group,family,genus,species,scientificname,commonname,country,state,...,year,month,day,status,comments,recordtype,disposal,museumcatnumber,freshmarineintro,references
0,1546947,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Canada,...,2018,8.0,NaN,unknown,Only one veliger found in the water sample. N...,Literature,NaN,NaN,Freshwater,"[{'key': 32886, 'refType': 'Web Page', 'year':..."
1,615085,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Manitoba,...,2013,10.0,17.0,unknown,Province of Manitoba news release. Found on hu...,Personal communication,NaN,NaN,Freshwater,[]
2,615297,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Manitoba,...,2013,10.0,11.0,unknown,A single adult was first discovered on a boat ...,Personal communication,NaN,NaN,Freshwater,[]
3,615300,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Manitoba,...,2013,10.0,NaN,unknown,Low density. A treatment of liquid potash was ...,Personal communication,NaN,NaN,Freshwater,[]
4,615301,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Manitoba,...,2013,10.0,NaN,unknown,Low density. A treatment of liquid potash was ...,Personal communication,NaN,NaN,Freshwater,[]

---
## CSV Reference Information

In [37]:
csv_ref_count = nas.ref_counts(csv_df)
print(nas.ref_string(csv_ref_count, limit=5))

--------
Most common reference 1

Total Occurrences:  2946
--------

--------
Most common reference 2

Source number:      1
Title:              Invader invaded: population dynamics of zebra mussels&nbsp;(<em>Dreissena polymorpha</em>) and quagga mussels (<em>Dreissena&nbsp;rostriformis bugensis</em>) in polymictic Oneida Lake, NY, USA&nbsp;(1992&ndash;2013)
Author:             Hetherington, A.L., L.G. Rudstam, R.L. Schneider, K.T. Holeck, C.W. Hotaling, J.E. Cooper, and J.R. Jackson
Publisher:          nan
Publisher Location: nan
Year:               2019
Reference Type:     Journal Article

Source number:      2
Title:              Lakewide zebra and quagga mussel summary, Oneida Lake, New York, 1992 to present
Author:             Rudstam, L.G.
Publisher:          Knowledge Network for Biocomplexity
Publisher Location: nan
Year:               2019
Reference Type:     Database

Total Occurrences:  681
--------

--------
Most common reference 3

Source number:      1
Title:              Zebra mussel sightings (unpublished data).
Author:             Ontario Federation of Anglers and Hunters.
Publisher:          nan
Publisher Location: nan
Year:               2006
Reference Type:     Database

Total Occurrences:  669
--------

--------
Most common reference 4

Source number:      1
Title:              Exotic aquatic mollusk collections in the Illinois Natural History Survey.
Author:             Vinsel, R., and J. Tiemann
Publisher:          Illinois Natural History Survey
Publisher Location: Champaign, IL
Year:               2016
Reference Type:     Database

Total Occurrences:  435
--------

--------
Most common reference 5

Source number:      1
Title:              Ohio River nonindigenous aquatic species 1992 - 2010 (unpublished).
Author:             Thomas, J., and J. Spaeth
Publisher:          Ohio River Valley Water Sanitation Commission
Publisher Location: Cincinnati, OH
Year:               2012
Reference Type:     Database

Total Occurrences:  301
--------