# Zebra Mussels
#### *Dreissena polymorpha*
---

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys

import numpy as np
import pandas as pd

import flbs_ais.nas as nas

In [3]:
search_result = nas.species_search('Dreissena', 'polymorpha')
search_string = nas.species_string(search_result)
print(search_string)

speciesID: 5
itis_tsn: 81339
group: Mollusks-Bivalves
family: Dreissenidae
genus: Dreissena
species: polymorpha
subspecies:
variety:
authority: (Pallas, 1771)
common_name: zebra mussel
native_exotic: Exotic
Fresh/Marine/Brackish: Freshwater

---
## Dataframe for zebra mussels

In [4]:
api_key = ""
with open("../tmp/api_key.txt", 'r') as file:
    api_key = file.readline()
api_df = nas.getdf(5, keep_columns=None, limit=-1, api_key=api_key)
print(f"Results: {len(api_df)}")
api_df.head()

Results: 7783

,specimennumber,speciesid,group,family,genus,species,scientificname,commonname,country,state,...,year,month,day,status,comments,recordtype,disposal,museumcatnumber,freshmarineintro,references
0,116074,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,Ohio,...,1990,3,NaN,established,Observed in and around the 61 cm and 76 cm int...,Personal communication,,,Freshwater,[]
1,116075,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,ONT,...,1990,4,NaN,established,Data from various monitoring programs.,Literature,,,Freshwater,"[{'key': 13755, 'refType': 'Other', 'year': 19..."
2,116076,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,New York,...,1990,4,NaN,established,Data from sampling plates and field observations.,Personal communication,,,Freshwater,[]
3,116077,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,New York,...,1990,9,17.0,established,Data from sampling plates and field observatio...,Personal communication,,,Freshwater,[]
4,116078,5,Mollusks-Bivalves,Dreissenidae,Dreissena,polymorpha,Dreissena polymorpha,zebra mussel,NaN,New York,...,1990,9,17.0,established,Data from sampling plates and buoy inspections.,Personal communication,,,Freshwater,[]

---
## List most common references

The first entry in this list is empty, meaning that there are 2,945 entries in this database without any reference information  
*Note: The output can be collapsed with the blue bar on the side*

In [23]:
api_ref_count = nas.ref_counts(api_df)
print(nas.ref_string(api_ref_count, limit=20))

--------
Most common reference 1

Total Occurrences:  2945
--------

--------
Most common reference 2

Source number:      1
Title:              Invader invaded: population dynamics of zebra mussels&nbsp;(<em>Dreissena polymorpha</em>) and quagga mussels (<em>Dreissena&nbsp;rostriformis bugensis</em>) in polymictic Oneida Lake, NY, USA&nbsp;(1992&ndash;2013)
Author:             Hetherington, A.L., L.G. Rudstam, R.L. Schneider, K.T. Holeck, C.W. Hotaling, J.E. Cooper, and J.R. Jackson
Publisher:
Publisher Location:
Year:               2019
Reference Type:     Journal Article

Source number:      2
Title:              Lakewide zebra and quagga mussel summary, Oneida Lake, New York, 1992 to present
Author:             Rudstam, L.G.
Publisher:          Knowledge Network for Biocomplexity
Publisher Location:
Year:               2019
Reference Type:     Database

Total Occurrences:  681
--------

--------
Most common reference 3

Source number:      1
Title:              Zebra mussel sightings (unpublished data).
Author:             Ontario Federation of Anglers and Hunters.
Publisher:
Publisher Location:
Year:               2006
Reference Type:     Database

Total Occurrences:  668
--------

--------
Most common reference 4

Source number:      1
Title:              Exotic aquatic mollusk collections in the Illinois Natural History Survey.
Author:             Vinsel, R., and J. Tiemann
Publisher:          Illinois Natural History Survey
Publisher Location: Champaign, IL
Year:               2016
Reference Type:     Database

Total Occurrences:  435
--------

--------
Most common reference 5

Source number:      1
Title:              Lakes and rivers with invasives species
Author:             Wisconsin Department of Natural Resources (WI DNR).
Publisher:          Wisconsin Department of Natural Resources
Publisher Location: Madison, WI
Year:               2017
Reference Type:     Database

Total Occurrences:  301
--------

--------
Most common reference 6

Source number:      1
Title:              Ohio River nonindigenous aquatic species 1992 - 2010 (unpublished).
Author:             Thomas, J., and J. Spaeth
Publisher:          Ohio River Valley Water Sanitation Commission
Publisher Location: Cincinnati, OH
Year:               2012
Reference Type:     Database

Total Occurrences:  301
--------

--------
Most common reference 7

Source number:      1
Title:              Midwest Invasive Species Information Network (MISIN)
Author:             Michigan State University Board of Trustees.
Publisher:          Michigan State University. Department of Entomology - Applied Spatial Ecology and Technical Services Laboratory
Publisher Location: East Lansing, MI
Year:               2019
Reference Type:     Database

Total Occurrences:  232
--------

--------
Most common reference 8

Source number:      1
Title:              Nonindigenous mollusks and amphipods in the upper Mississippi drainage.
Author:             Angradi, T.R.
Publisher:          US Environmental Protection Agency
Publisher Location: Duluth, MN
Year:               2018
Reference Type:     Database

Source number:      2
Title:              Occurrence of the quagga mussel (<em>Dreissena bugensis</em>) and the zebra mussel (<em>Dreissena polymorpha</em>) in the Upper Mississippi River system.
Author:             Grigorovich, I.A., T.R. Angradi, and C.A. Stepien
Publisher:
Publisher Location:
Year:               2008
Reference Type:     Journal Article

Total Occurrences:  195
--------

--------
Most common reference 9

Source number:      1
Title:              EPA Monitoring Data.
Author:             EPA Great Lakes National Program Office.
Publisher:
Publisher Location:
Year:               2008
Reference Type:     Database

Total Occurrences:  183
--------

--------
Most common reference 10

Source number:      1
Title:              Midwest Invasive Species Information Network (MISIN)
Author:             Michigan State University Board of Trustees.
Publisher:          Michigan State University. Department of Entomology - Applied Spatial Ecology and Technical Services Laboratory
Publisher Location: East Lansing, MI
Year:               2019
Reference Type:     Database

Source number:      2
Title:              Illinois Database of Aquatic Non-native Species
Author:             Loyola University Chicago
Publisher:          GISIN
Publisher Location: Fort Collins, CO
Year:               2013
Reference Type:     Database

Total Occurrences:  167
--------

--------
Most common reference 11

Source number:      1
Title:              Zebra mussel data points in Missouri.
Author:             McMurray, Stephen (Missouri Dept. of Conservation).
Publisher:          Missouri Dept of Conservation.
Publisher Location:
Year:               2009
Reference Type:     Database

Total Occurrences:  139
--------

--------
Most common reference 12

Source number:      1
Title:              Distribution of zebra mussels on Canadian navigation buoys on the Great Lakes and upper St. Lawrence River, December 1992.
Author:             Wormington, A., C.A. Timmins, and R.M. Dermott.
Publisher:          Fisheries and Oceans Canada
Publisher Location: Burlington, Ontario
Year:               1993
Reference Type:     Report

Total Occurrences:  99
--------

--------
Most common reference 13

Source number:      1
Title:              Zebra Mussel Locations.
Author:             Wisconsin Department of Natural Resources (WIDNR)
Publisher:
Publisher Location:
Year:               2014
Reference Type:     Web Page

Total Occurrences:  75
--------

--------
Most common reference 14

Source number:      1
Title:              EDDMapS: Early detection and distribution mapping system
Author:             Center for Invasive Species and Ecosystem Health.
Publisher:          The University of Georgia
Publisher Location: Tifton, GA
Year:               2019
Reference Type:     Database

Total Occurrences:  74
--------

--------
Most common reference 15

Source number:      1
Title:              Dispersal mechanisms for zebra mussels: population genetics supports clustered invasions over spread from hub lakes in Minnesota.
Author:             Mallez, S., and M. McCartney
Publisher:
Publisher Location:
Year:               2018
Reference Type:     Journal Article

Total Occurrences:  71
--------

--------
Most common reference 16

Source number:      1
Title:              Aquatic Invasives Data and Maps.
Author:             Wisconsin Dept. of Natural Resources.
Publisher:          Wisconsin Dept of Natural Resources, Madison, Wisconsin.
Publisher Location:
Year:               2010
Reference Type:     Database

Total Occurrences:  70
--------

--------
Most common reference 17

Source number:      1
Title:              2012 Eastern Finger Lakes Benthic Aquatic Invertebrate Assessment (unpublished).
Author:             Wunderlich, M.
Publisher:
Publisher Location:
Year:               2012
Reference Type:     Database

Total Occurrences:  57
--------

--------
Most common reference 18

Source number:      1
Title:              OFAH Database All Species - 2009 Download.
Author:             Ontario Federation of Anglers and Hunters.
Publisher:
Publisher Location:
Year:               2009
Reference Type:     Database

Total Occurrences:  55
--------

--------
Most common reference 19

Source number:      1
Title:              Invasive Species Catch 2017
Author:             Bowen, A.
Publisher:          U.S. Fish and Wildlife Service
Publisher Location: Alpena, MI
Year:               2018
Reference Type:     Database

Total Occurrences:  46
--------

--------
Most common reference 20

Source number:      1
Title:              Great Lakes Coastal Monitoring Project: inverts dataset (through 2013)
Author:             Brady, V.
Publisher:          Environmental Protection Agency, Great Lakes National Program Office
Publisher Location: Chicago, IL
Year:               2015
Reference Type:     Database

Total Occurrences:  44
--------

---
## CSV Information
We can see that in this case, the CSV file only appears to have the same number of data entries as the API search.

In [18]:
csv_df = nas.process_csv_df("../tmp/NAS-Data-ZebraMussel.csv")
print(f"Results: {len(csv_df)}")
csv_df.head()

Results: 7785

,specimennumber,speciesid,group,family,genus,species,scientificname,commonname,country,state,...,year,month,day,status,comments,recordtype,disposal,museumcatnumber,freshmarineintro,references
0,1546947,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Canada,...,2018,8.0,NaN,unknown,Only one veliger found in the water sample. N...,Literature,NaN,NaN,Freshwater,"[{'key': 32886, 'refType': 'Web Page', 'year':..."
1,615085,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Manitoba,...,2013,10.0,17.0,unknown,Province of Manitoba news release. Found on hu...,Personal communication,NaN,NaN,Freshwater,"[{'key': nan, 'refType': nan, 'year': nan, 'au..."
2,615297,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Manitoba,...,2013,10.0,11.0,unknown,A single adult was first discovered on a boat ...,Personal communication,NaN,NaN,Freshwater,"[{'key': nan, 'refType': nan, 'year': nan, 'au..."
3,615300,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Manitoba,...,2013,10.0,NaN,unknown,Low density. A treatment of liquid potash was ...,Personal communication,NaN,NaN,Freshwater,"[{'key': nan, 'refType': nan, 'year': nan, 'au..."
4,615301,5,Mollusks-Bivalves,Dreissenidae,NaN,NaN,Dreissena polymorpha,zebra mussel,Canada,Manitoba,...,2013,10.0,NaN,unknown,Low density. A treatment of liquid potash was ...,Personal communication,NaN,NaN,Freshwater,"[{'key': nan, 'refType': nan, 'year': nan, 'au..."

---
## CSV Reference Information
NOTE: Reference information for CSV files is not currently functional

In [22]:
csv_ref_count = nas.ref_counts(csv_df)
print(nas.ref_string(csv_ref_count, limit=20))

--------
Most common reference 1

Source number:      1
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 2

Source number:      1
Title:              EPA Monitoring Data.
Author:             EPA Great Lakes National Program Office.
Publisher:          nan
Publisher Location: nan
Year:               2008
Reference Type:     Database

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 3

Source number:      1
Title:              Zebra mussel data points in Missouri.
Author:             McMurray, Stephen (Missouri Dept. of Conservation).
Publisher:          Missouri Dept of Conservation.
Publisher Location: nan
Year:               2009
Reference Type:     Database

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 4

Source number:      1
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 5

Source number:      1
Title:              Joint Aquatic Invasive Species Survey, 2010
Author:             Central Hardwoods Invasive Plant Network.
Publisher:          University of Georgia
Publisher Location: Athens, GA
Year:               2010
Reference Type:     Database

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 6

Source number:      1
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 7

Source number:      1
Title:              Ohio River nonindigenous aquatic species 1992 - 2010 (unpublished).
Author:             Thomas, J., and J. Spaeth
Publisher:          Ohio River Valley Water Sanitation Commission
Publisher Location: Cincinnati, OH
Year:               2012
Reference Type:     Database

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 8

Source number:      1
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 9

Source number:      1
Title:              Nonindigenous mollusks and amphipods in the upper Mississippi drainage.
Author:             Angradi, T.R.
Publisher:          US Environmental Protection Agency
Publisher Location: Duluth, MN
Year:               2018
Reference Type:     Database

Source number:      2
Title:              Occurrence of the quagga mussel (<em>Dreissena bugensis</em>) and the zebra mussel (<em>Dreissena polymorpha</em>) in the Upper Mississippi River system.
Author:             Grigorovich, I.A., T.R. Angradi, and C.A. Stepien
Publisher:          nan
Publisher Location: nan
Year:               2008
Reference Type:     Journal Article

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 10

Source number:      1
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 11

Source number:      1
Title:              Invader invaded: population dynamics of zebra mussels&nbsp;(<em>Dreissena polymorpha</em>) and quagga mussels (<em>Dreissena&nbsp;rostriformis bugensis</em>) in polymictic Oneida Lake, NY, USA&nbsp;(1992&ndash;2013)
Author:             Hetherington, A.L., L.G. Rudstam, R.L. Schneider, K.T. Holeck, C.W. Hotaling, J.E. Cooper, and J.R. Jackson
Publisher:          nan
Publisher Location: nan
Year:               2019
Reference Type:     Journal Article

Source number:      2
Title:              Lakewide zebra and quagga mussel summary, Oneida Lake, New York, 1992 to present
Author:             Rudstam, L.G.
Publisher:          Knowledge Network for Biocomplexity
Publisher Location: nan
Year:               2019
Reference Type:     Database

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 12

Source number:      1
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 13

Source number:      1
Title:              Nonindigenous mollusks and amphipods in the upper Mississippi drainage.
Author:             Angradi, T.R.
Publisher:          US Environmental Protection Agency
Publisher Location: Duluth, MN
Year:               2018
Reference Type:     Database

Source number:      2
Title:              Occurrence of the quagga mussel (<em>Dreissena bugensis</em>) and the zebra mussel (<em>Dreissena polymorpha</em>) in the Upper Mississippi River system.
Author:             Grigorovich, I.A., T.R. Angradi, and C.A. Stepien
Publisher:          nan
Publisher Location: nan
Year:               2008
Reference Type:     Journal Article

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 14

Source number:      1
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 15

Source number:      1
Title:              Zebra mussel data points in Missouri.
Author:             McMurray, Stephen (Missouri Dept. of Conservation).
Publisher:          Missouri Dept of Conservation.
Publisher Location: nan
Year:               2009
Reference Type:     Database

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 16

Source number:      1
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      2
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Total Occurrences:  1
--------

--------
Most common reference 17

Source number:      1
Title:              Nonindigenous mollusks and amphipods in the upper Mississippi drainage.
Author:             Angradi, T.R.
Publisher:          US Environmental Protection Agency
Publisher Location: Duluth, MN
Year:               2018
Reference Type:     Database

Source number:      2
Title:              Occurrence of the quagga mussel (<em>Dreissena bugensis</em>) and the zebra mussel (<em>Dreissena polymorpha</em>) in the Upper Mississippi River system.
Author:             Grigorovich, I.A., T.R. Angradi, and C.A. Stepien
Publisher:          nan
Publisher Location: nan
Year:               2008
Reference Type:     Journal Article

Source number:      3
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      4
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      5
Title:              nan
Author:             nan
Publisher:          nan
Publisher Location: nan
Year:               nan
Reference Type:     nan

Source number:      6